force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>Participant-{000000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ParticipantSelectors.cls
public with sharing class ParticipantSelectors {
    public static List<Participant__c> queryParticipantsFromTrainings(List<Training__c> trainings) {
        return [
            SELECT Id
            FROM Participant__c
            WHERE Training__c IN :trainings
        ];
    }
    
    public static List<Participant__c> queryParticipantsByIds(Set<Id> participantIds) {
        return [
            SELECT Id, Training__r.Name, Contact_Name__c, Contact_Name__r.Name, Contact_Name__r.Email
            FROM Participant__c 
            WHERE Id IN :participantIds
        ];
    }
}