force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>Participant-{000000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RegistrationConfirmationQueueableTest.cls
@IsTest
public with sharing class RegistrationConfirmationQueueableTest {
    
    @testSetup static void setup() {
        Contact contact = TestDataFactory.createNewContact('Eason', 'Recto');
        insert contact;
        
        Restaurant__c restaurant = TestDataFactory.createNewRestaurant('Testaurant');
        insert restaurant;
        
        Training__c training = TestDataFactory.createNewTraining(contact, restaurant, Date.today().addDays(3));
        insert training;
    }
    
	@isTest 
    static void testRegistrationConfirmationQueueable() {      
        
        Contact testContact = [
            SELECT Id
            FROM Contact
            LIMIT 1
        ];
        
        Training__c testTraining = [
            SELECT Id
            FROM Training__c
            LIMIT 1
        ];
        
        Participant__c testParticipant = new Participant__c();
        testParticipant.Status__c = 'Active';
        testParticipant.Training__c = testTraining.Id;
        testParticipant.Contact_Name__c = testContact.Id;

        Test.startTest();
        insert testParticipant;
        Test.stopTest();
        
        AsyncApexJob job = [
            SELECT Id, Status
            FROM AsyncApexJob
            LIMIT 1
        ];
        
        Assert.areEqual('Completed', job.Status);
    }
}