force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>Participant-{000000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/PaymentLink__c.field-meta.xml
<CustomField>
    <fullName>PaymentLink__c</fullName>
    <label>Payment Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentLinkCallout.cls
public with sharing class PaymentLinkCallout {
    public class EmptyParticipantsListException extends Exception {}

    private static final String PAYMENT_LINK_ENDPOINT = 'https://735ef563-176d-431c-85ce-2cc07056ef03.mock.pstmn.io/payments/link';

    public static void requestPaymentLink(List<Participant__c> participants) {
        if(participants.isEmpty()) {
            throw new EmptyParticipantsListException('The list of participants is empty');
        }
        
        String endpoint = PAYMENT_LINK_ENDPOINT;
        
        for (Participant__c participant : participants) {
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpoint);
            request.setHeader('content-type', 'application/json');
            request.setMethod('GET');

            Http http = new Http();

            try {
                HttpResponse response = http.send(request);
                PaymentPayload payload = PaymentPayload.parse(response.getBody());
                String link = payload.Payer.link;

                participant.PaymentLink__c = link;
            } catch(Exception e) {
                throw new PaymentLinkAPIException(e);
            }
        }

        try {
            update participants;
        } catch(Exception e) {
            throw new PaymentLinkCalloutCustomException.DMLException(e);
        }
        
    }

    public static void sendPaymentEmail(Participant__c participant) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = createEmailToSendPaymentLink(participant);
        emails.add(mail);
        Messaging.sendEmail(emails);
    }

    private static Messaging.SingleEmailMessage createEmailToSendPaymentLink(Participant__c participant) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(participant.Contact_Name__c);
        mail.setWhatId(participant.Id);
        mail.setHTMLBody('Dear ' + participant.Contact_Name__r.Name + ',\n\n' +
                         'To complete your registration, please make a payment by clicking on the link below:\n\n' + 
                         participant.PaymentLink__c + '\n\n' +
                         'We are lookingforward to seeing you!\n\n' +
                         'Best regards,\n' + 
                         'Training Management System'
                        );
        return mail;
    }
}