force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>Participant-{000000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchSyncToERP.cls
public class BatchSyncToERP implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Name, Status__c FROM Participant__c';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Participant__c> participants) {
        for(Participant__c participant : participants) {
            ERPCallout.sendParticipantToERP(participant);
        }
        try {
            ERPCallout.sendParticipantToERPFromBatch(participants);

        } catch (DMLException e) {
            HandleCustomException.LogException(e);

        } catch (Exception e) {
            HandleCustomException.LogException(e);

        } finally {
        }
    }

    public void finish(Database.BatchableContext bc) {}
}